# Generated by Django 5.2 on 2025-04-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "renda_familiar",
                    models.CharField(
                        choices=[
                            ("menos_de_um", "Menos de um salário mínimo"),
                            ("ate_um", "Até um salário mínimo"),
                            ("dois_a_tres", "De dois a três salários mínimos"),
                            ("tres_a_quatro", "De três a quatro salários mínimos"),
                            ("quatro_a_cinco", "De quatro a cinco salários mínimos"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nome_civil", models.CharField(max_length=255)),
                (
                    "nome_social",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rg_numero", models.CharField(max_length=20)),
                ("rg_orgao_expedidor", models.CharField(max_length=50)),
                ("cpf", models.CharField(max_length=14)),
                ("data_nascimento", models.DateField()),
                ("rg_anexo", models.FileField(upload_to="uploads/rg/")),
                (
                    "territorio",
                    models.CharField(
                        choices=[
                            ("rmn", "Região Metropolitana de Natal"),
                            ("agreste", "Agreste / Litoral Sul"),
                            ("mato_grande", "Mato Grande"),
                            ("potengi", "Potengi"),
                            ("trairi", "Trairí"),
                            ("sertao_cabugi", "Sertão Central Cabugi / Litoral Norte"),
                            ("serido", "Seridó"),
                            ("assu_mossoro", "Assú / Mossoró"),
                            ("sertao_apodi", "Sertão do Apodi"),
                            ("alto_oeste", "Alto Oeste"),
                        ],
                        max_length=30,
                    ),
                ),
                ("telefone", models.CharField(max_length=20)),
                (
                    "genero_sexualidade",
                    models.CharField(
                        choices=[
                            ("travesti", "Travesti"),
                            ("mulher_transexual", "Mulher Transexual"),
                            ("homem_transexual", "Homem Transexual"),
                            ("intersexual", "Intersexual"),
                            ("nao_binario", "Não Binárie"),
                            ("trans_masculine", "Trans Masculine"),
                            ("outro", "Outro"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "etnia",
                    models.CharField(
                        choices=[
                            ("negra", "Negra"),
                            ("indigena", "Indígena"),
                            ("cigana", "Cigana"),
                            ("quilombola", "Quilombola"),
                            ("parda", "Parda"),
                            ("branca", "Branca"),
                            ("amarela", "Amarela"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
