# Generated by Django 5.2 on 2025-04-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscricoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricao",
            name="pontuacao",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="inscricao",
            name="populacao_de_rua",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="inscricao",
            name="genero_sexualidade",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="inscricao",
            name="nome_civil",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="inscricao",
            name="nome_social",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="inscricao",
            name="renda_familiar",
            field=models.CharField(
                choices=[
                    ("<1", "menos de um salário mínimo"),
                    ("1", "até um salário mínimo"),
                    ("2-3", "de dois a três salários mínimos"),
                    ("3-4", "de três a quatro salários mínimos"),
                    ("4-5", "de quatro a cinco salários mínimos"),
                    (">5", "mais de cinco salários mínimos"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="inscricao",
            name="rg_anexo",
            field=models.FileField(upload_to="documentos/"),
        ),
        migrations.AlterField(
            model_name="inscricao",
            name="rg_numero",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="inscricao",
            name="territorio",
            field=models.CharField(max_length=100),
        ),
    ]
