# Generated by Django 5.2 on 2025-04-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_inscricao_pontuacao_inscricao_populacao_de_rua_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='genero_sexualidade',
            field=models.CharField(choices=[('travesti', 'Travesti'), ('mulher_transexual', 'Mulher Transexual'), ('homem_transexual', 'Homem Transexual'), ('intersexual', 'Intersexual'), ('nao_binario', 'Não Binárie'), ('trans_masculine', 'Trans Masculine'), ('outro', 'Outro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='territorio',
            field=models.CharField(choices=[('metropolitana', 'Território Região Metropolitana de Natal'), ('agreste', 'Território Agreste / Litoral Sul'), ('mato_grande', 'Território Mato Grande'), ('potengi', 'Território Potengi'), ('trairi', 'Território Trairí'), ('sertao_central', 'Território Sertão Central Cabugi / Litoral Norte'), ('serido', 'Território Seridó'), ('assu_mossoro', 'Território Assú / Mossoró'), ('apodi', 'Território Sertão do Apodi'), ('alto_oeste', 'Território Alto Oeste')], max_length=50),
        ),
    ]
